# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Update Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.23
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ezeholz
          template: "@bigger"
          setup_community_templates: ezeholz/metrics@templates:bigger+trust
          config_padding: 0, 23 + 11%
          filename: metrics.*
          committer_gist: "4bc3474185f69e7d4fe8e610ce6a9cc6"
          output_action: gist
          extras_css: |
            h1 {
              justify-content: center
            }
            .row section:nth-child(2) :nth-child(n) {
                flex-direction: row-reverse;
            }
            .language {
                max-width: 800px
            }
            .language .bar {
                width: 100%
            }
            .field.language.details small :nth-child(n) {
                padding: 0 0 0 40px
            }
            .language .row section:nth-child(2) :nth-child(n) {
                flex-direction: row;
            }
            .language .row {
              width: 100%;
            }
          base: header, activity, community, repositories
          config_timezone: America/Buenos_Aires
          repositories_affiliations: owner, collaborator
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_aliases: "JavaScript:JS"
          plugin_languages_threshold: 2%
          plugin_languages_skipped: ${{ secrets.LSkipped }}
          plugin_lines: yes
