# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ezeholz
          template: "@bigger"
          setup_community_templates: ezeholz/metrics@templates:bigger+trust
          config_padding: 0, 23 + 11%
          filename: metrics.*
          committer_gist: "4bc3474185f69e7d4fe8e610ce6a9cc6"
          output_action: gist
          extras_css: |
            h1 {
              justify-content: center
            }
            section:nth-child(2) section:nth-of-type(2) div:nth-of-type(3) path:first-child, section:nth-child(3) section:nth-of-type(2) div:nth-of-type(1) path:first-child {
              // fill: red
            }
            section:nth-child(2) section:nth-of-type(2) div:nth-of-type(4) path:first-child, section:nth-child(3) section:nth-of-type(2) div:nth-of-type(2) path:first-child {
              // fill: yellow
            }
          base: header, activity, community, repositories
          config_timezone: America/Buenos_Aires
          repositories_affiliations: owner, collaborator
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_aliases: "JavaScript:JS"
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_skipped: ${{ secrets.SKIPPED }}
